"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cspujvvbhbas4yxq$)g_&@a!$mr-p2^rj(!l^xp2977y870!ie'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
  '*'
]


# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  "rest_framework",
  "corsheaders",
  "apis",
  "authentications",
  "application",
  "approval",
  "users",
  "systemsettings",
  "career",
]

MIDDLEWARE = [
  "corsheaders.middleware.CorsMiddleware",
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.sqlite3',
#     'NAME': BASE_DIR / 'db.sqlite3',
#   }
# }

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'leave_connect_db',
    'USER': 'root',
    'HOST': '',
    'PORT': '3308',
    'PASSWORD': 'password',
  }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
  'version': 1,
  'disable_existing_loggers': False,
  'handlers': {
    'console': {
      'level': 'DEBUG',
      'class': 'logging.StreamHandler',
    }
  },
  # 'loggers': {
  #   'django.db.backends': {
  #     'level': 'DEBUG',
  #     'handlers': ['console'],
  #   },
  # }
}

# set-cookieでSecureをtrueに設定する
# HTTPS接続の場合のみ機能する
# SESSION_COOKIE_SECURE = True
# set-cookieでSamesSiteをNoneに設定する
# default='Lax'
# SESSION_COOKIE_SAMESITE = 'None'

# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = [
  'http://192.168.0.253:3000'
]

CSRF_TRUSTED_ORIGINS = [
]

CORS_ALLOW_HEADERS = (
  'accept',
  'accept-encoding',
  'authorization',
  'content-type',
  'dnt',
  'origin',
  'user-agent',
  'x-csrftoken',
  'x-requested-with',
  'access-control-allow-origin',
  # 'access-control-allow-credentials',
)

# JWT生成 シークレットキー
JWT_SECRET_KEY = 'aa785c482395933b5fa6535b976653894a10b258209f7f5c43416129a6249774'
# JWT生成 アルゴリズム
JWT_ALGORITHMS = 'HS256'
# パスワードハッシュ化 アルゴリズム
PASS_ALGORITHMS = 'sha1'
# パスワード シークレットソルト
PASS_SECRET_SALT = 'TgX7s3nwYPNq'
# 初期パスワード
INITIAL_PASSWORD = 'password'
# 年次有給休暇申請タイプ値
PAID_HOLIDAY_VALUE = 0
# 有効なユーザのステータス
USER_EFFECTIVE_STATUS = 1
# スキル管理シート出力フォルダ
CAREER_SHEET_OUTPUT_DIR_PATH = 'temp'
# スキルシ管理シートプレフィックス
CAREER_SHEET_PREFIX = '/スキル表_'
